# Generated by Django 5.0 on 2024-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='examples@gmail.com', max_length=250, null=True),
        ),
    ]
