# Generated by Django 5.0 on 2024-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortgroup',
            name='name',
            field=models.CharField(choices=[('Cohort 1', 'Cohort 1'), ('Cohort 2', 'Cohort 2'), ('Cohort 3', 'Cohort 3')], max_length=200),
        ),
    ]
